### ISSUE TITLE
Integration with vault

### ISSUE THREAD

**Issue by jianhang33** [gardener/oidc-webhook-authenticator#123]
**What would you like to be added**:
Integration with vault, specifically I'd like to know if the application periodically reloads the certificate from file /var/run/certs/tls.crt as specified in the following

``` - name: authenticator
        image: oidc-webhook-authenticator:latest
        imagePullPolicy: IfNotPresent
        args:
        - --tls-cert-file=/var/run/certs/tls.crt
        - --tls-private-key-file=/var/run/certs/tls.key
```

**Why is this needed**:
certificate has lifetime, which shouldn't be too long, and therefore periodical rotating the certificate is required. If the application doesn't periodically reloads the certificate, a restart of the application is required after the certificate is updated.

**Comment by dimityrmirchev** [comment]
Hi @jianhang33

Since we use the k8s apiserver package under the hood I guess the certificates will be reloaded every one minute. At least this is my understanding from [looking at the implementation](https://github.com/kubernetes/kubernetes/blob/9e644106593f3f4aa98f8a84b23db5fa378900bd/staging/src/k8s.io/apiserver/pkg/server/dynamiccertificates/tlsconfig.go#L249), however I am not 100% sure that this is the case. This can be tested if one really wants to. Another thing to mention is that if you are using the helm chart to deploy OWA the secret hash is [added as an annotation on the deployment](https://github.com/gardener/oidc-webhook-authenticator/blob/d60ada3201fab32b18136606f40c0bc8b80a1e13/charts/oidc-webhook-authenticator/charts/runtime/templates/deployment.yaml#L32) so if the certificates change the application will rollout during a helm release deployment.

**Comment by jianhang33** [comment]
Hi @dimityrmirchev
Thanks for your reply. I'll test it and update the finding here. 

By the way, I actually just wanted to ask a question, but I didn't know any other ways to do it and therefore created this issue. Is there a place to ask questions or a mailing list to do it?

**Comment by dimityrmirchev** [comment]
If you are interested in gardener topics you can find contact info on our site's [community page](https://gardener.cloud/community/). For this specific project we do not have any dedicated channels since there are not many questions or discussions coming our way so opening an issue is just fine. Another thing that I wanted to mention is that the K8s community has accepted a KEP w.r.t [structured authentication](https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3331-structured-authentication-configuration) which will basically provide the functionality of the oidc-webhook-authenticator and more, but built into k8s itself. So this is something that you might want to follow/adopt when the feature becomes Beta/GA.

**Comment by jianhang33** [comment]
I have verified that the application reloads certificate and key periodically.

**Comment by jianhang33** [comment]
close
