### ISSUE TITLE
Add extra claims extraction from JWT token

### ISSUE THREAD

**Issue by sgaist** [gardener/oidc-webhook-authenticator#127]
**What would you like to be added**:

Support to extract additional claims from the JWT token and add them to the Extra field of the UserInfo structure

**Why is this needed**:

This allows cluster administrators to re-use information already available in the token for later processing for example in a different webhook (validating or mutating).

**Current state**:

This webhook follows the same implementation as the kube api server meaning that the UserInfo structure is populated with the username and groups extracted from the token. In addition to these, webhook specific extra data are added.

The OIDC client configuration (be it kubectl or something else) can include extra scopes that will provide more claims to use however the implementation as is does not allow to query them (it is the same for the kube api server).

There's current work for [KEP 3331](https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3331-structured-authentication-configuration#design-details) that will implement support for additional claims extraction and more however it won't be available before 1.29.

In the mean time, this hook would be a very good place to implement the claim extraction part. If interested, I have a basic implementation of that feature and would be happy to discuss and contribute it to this project.

**Comment by dimityrmirchev** [comment]
Hello @sgaist and thank you for taking interest in this project.

With [KEP 3331](https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3331-structured-authentication-configuration#design-details) knocking on the front door I am somehow reluctant to spend more development time or make big changes to this project since it will probably become obsolete with the delivery of Structured Authentication in k8s. However if you are willing to implement this functionality I can review it.

My first thoughts are that the additional extracted claims should go in [this piece of code](https://github.com/gardener/oidc-webhook-authenticator/blob/955e2ac7fe421b637eded75256b8f0fc48eb62d8/controllers/authentication/openidconnect_controller.go#L270) and should be prefixed with "gardener.cloud/user/". What users want additionally extracted can be configured in the `openidconnect` [CDR](https://github.com/gardener/oidc-webhook-authenticator/blob/955e2ac7fe421b637eded75256b8f0fc48eb62d8/apis/authentication/v1alpha1/openidconnect_types.go#L41) under the name "extraClaims" (or maybe something similar).

**Comment by sgaist** [comment]
Hi @dimityrmirchev,

That's fine for me, I already have a working implementation with tests that is being used. I need to change the field key creation to include your prefix but other than that it should be ready for review.

Note that I am a go beginner so I would be more than happy to revise the implementation if there are better ways.
